resources:
- ../crds
- ../operator
- ../scorecard
- ../samples

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: monitoring-stack-operator
    newName: quay.io/sthaha/monitoring-stack-operator
    newTag: 0.0.1
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args
      value: [--deploy-prometheus-operator-crds=false]
  target:
    kind: Deployment
    name: monitoring-stack-operator
