apiVersion: v1
kind: Template
metadata:
  name: selectorsyncset-template

parameters:
  - name: REGISTRY_IMG
    required: true
    value: quay.io/rhobs/observability-operator-catalog
  - name: CHANNEL
    value: development
    required: true
  - name: IMAGE_DIGEST
    required: true
    value: eee088e78ecbaafdc572188398ceb463e63c365f1023a0301742be2a8e0e4c29
  - name: RESOURCE_LIMIT_CPU
    required: true
    value: 200m
  - name: RESOURCE_REQUEST_CPU
    required: true
    value: 100m
  - name: RESOURCE_LIMIT_MEMORY
    required: true
    value: 300Mi
  - name: RESOURCE_REQUEST_MEMORY
    required: true
    value: 150m

objects:
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      name: observability-operator
    spec:
      clusterDeploymentSelector:
        matchLabels:
          api.openshift.com/managed: "true"
      resourceApplyMode: Sync
      resources:
        - apiVersion: v1
          kind: Namespace
          metadata:
            annotations:
              openshift.io/node-selector: ''
            name: openshift-observability-operator
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      name: observability-operator-hypershift
    spec:
      clusterDeploymentSelector:
        matchLabels:
          api.openshift.com/managed: 'true'
        matchExpressions:
          - key: ext-hypershift.openshift.io/cluster-type
            operator: In
            values:
              - management-cluster
              - service-cluster
      resourceApplyMode: Sync
      resources:
        - apiVersion: operators.coreos.com/v1alpha1
          kind: CatalogSource
          metadata:
            name: observability-operator-catalog
            namespace: openshift-observability-operator
          spec:
            displayName: Red Hat Observability Operator
            image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
            publisher: OSD Red Hat Addons
            sourceType: grpc
            grpcPodConfig:
              securityContextConfig: restricted
              nodeSelector:
                node-role.kubernetes.io: infra
              tolerations:
                - effect: NoSchedule
                  key: node-role.kubernetes.io/infra
                  operator: Exists
        - apiVersion: operators.coreos.com/v1alpha2
          kind: OperatorGroup
          metadata:
            name: observability-operator-og
            namespace: openshift-observability-operator
        - apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: observability-operator
            namespace: openshift-observability-operator
          spec:
            channel: ${CHANNEL}
            name: observability-operator
            source: observability-operator-catalog
            sourceNamespace: openshift-observability-operator
            config:
              resources:
                limits:
                  cpu: ${RESOURCE_LIMIT_CPU}
                  memory: ${RESOURCE_LIMIT_MEMORY}
                requests:
                  cpu: ${RESOURCE_REQUEST_CPU}
                  memory: ${RESOURCE_REQUEST_MEMORY}
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      name: observability-operator-rhoam
    spec:
      clusterDeploymentSelector:
        matchLabels:
          api.openshift.com/addon-managed-api-service: 'true'
      resourceApplyMode: Sync
      resources:
        - apiVersion: operators.coreos.com/v1alpha1
          kind: CatalogSource
          metadata:
            name: observability-operator-catalog
            namespace: openshift-observability-operator
          spec:
            displayName: Red Hat Observability Operator
            image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
            publisher: OSD Red Hat Addons
            sourceType: grpc
            grpcPodConfig:
              securityContextConfig: restricted
              nodeSelector:
                node-role.kubernetes.io: infra
              tolerations:
                - effect: NoSchedule
                  key: node-role.kubernetes.io/infra
                  operator: Exists
        - apiVersion: operators.coreos.com/v1alpha2
          kind: OperatorGroup
          metadata:
            name: observability-operator-og
            namespace: openshift-observability-operator
        - apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: observability-operator
            namespace: openshift-observability-operator
          spec:
            channel: ${CHANNEL}
            name: observability-operator
            source: observability-operator-catalog
            sourceNamespace: openshift-observability-operator
            config:
              resources:
                limits:
                  cpu: ${RESOURCE_LIMIT_CPU}
                  memory: ${RESOURCE_LIMIT_MEMORY}
                requests:
                  cpu: ${RESOURCE_REQUEST_CPU}
                  memory: ${RESOURCE_REQUEST_MEMORY}
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      name: observability-operator-rhoam-int
    spec:
      clusterDeploymentSelector:
        matchLabels:
          api.openshift.com/addon-managed-api-service-internal: 'true'
      resourceApplyMode: Sync
      resources:
        - apiVersion: operators.coreos.com/v1alpha1
          kind: CatalogSource
          metadata:
            name: observability-operator-catalog
            namespace: openshift-observability-operator
          spec:
            displayName: Red Hat Observability Operator
            image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
            publisher: OSD Red Hat Addons
            sourceType: grpc
            grpcPodConfig:
              securityContextConfig: restricted
              nodeSelector:
                node-role.kubernetes.io: infra
              tolerations:
                - effect: NoSchedule
                  key: node-role.kubernetes.io/infra
                  operator: Exists
        - apiVersion: operators.coreos.com/v1alpha2
          kind: OperatorGroup
          metadata:
            name: observability-operator-og
            namespace: openshift-observability-operator
        - apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: observability-operator
            namespace: openshift-observability-operator
          spec:
            channel: ${CHANNEL}
            name: observability-operator
            source: observability-operator-catalog
            sourceNamespace: openshift-observability-operator
            config:
              resources:
                limits:
                  cpu: ${RESOURCE_LIMIT_CPU}
                  memory: ${RESOURCE_LIMIT_MEMORY}
                requests:
                  cpu: ${RESOURCE_REQUEST_CPU}
                  memory: ${RESOURCE_REQUEST_MEMORY}
