run:
  deadline: 10m

linters:
  enable:
    - gci

issues:
  exclude-rules:
   - path: _test.go
     linters:
     - errcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/rhobs/observability-operator)
