apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-stack-operator
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: monitoring-stack-operator
    app.kubernetes.io/part-of: monitoring-stack-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: monitoring-stack-operator
      app.kubernetes.io/component: operator
  endpoints:
  - port: metrics
