---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - console.openshift.io
  resources:
  - consoleplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loki.grafana.com
  resources:
  - application
  - audit
  - infrastructure
  verbs:
  - get
- apiGroups:
  - monitoring.rhobs
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/finalizers
  - monitoringstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - thanosqueriers
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - thanosqueriers/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - thanosqueriers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - observability.openshift.io
  resources:
  - uiplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.openshift.io
  resources:
  - uiplugins/finalizers
  - uiplugins/status
  verbs:
  - get
  - update
- apiGroups:
  - observability.openshift.io
  resources:
  - uiplugins/status
  verbs:
  - get
  - update
- apiGroups:
  - operator.openshift.io
  resources:
  - consoles
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  - nonroot-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - tempo.grafana.com
  resources:
  - tempostacks
  verbs:
  - list
