kind: Service
apiVersion: v1
metadata:
  name: observability-operator
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: observability-operator
    app.kubernetes.io/part-of: observability-operator
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: observability-operator-tls
spec:
  selector:
    app.kubernetes.io/name: observability-operator
    app.kubernetes.io/component: operator
  ports:
  - name: metrics
    port: 8080
