name: e2e
on:
  pull_request:
  push:
    branches:
      - 'release-*'
      - 'main'
    tags:
      - 'v*'
env:
  kind-version: 'v0.11.1'
  kind-image: 'kindest/node:v1.22.0'
  golang-version: '1.16'

jobs:
  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.golang-version }}
      - name: Build images
        run: |
          make operator-image
      - name: Start KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: ${{ env.kind-version }}
          image: ${{ env.kind-image }}
          wait: 300s
      - name: Wait for cluster to finish bootstraping
        run: |
          kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s
          kubectl cluster-info
          kubectl get pods -A
      - name: Load images
        run: |
          kind load docker-image monitoring-stack-operator:$(cat VERSION)
      - name: Run tests
        run: go test ./test/e2e/...
