name: checks
on:
  pull_request:

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  github-actions-yaml-lint:
    runs-on: ubuntu-latest
    name: Github Actions yaml linter
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1

  lint:
    runs-on: ubuntu-latest
    name: Run all lints
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Use tools cache
        uses: ./.github/tools-cache

      - name: golangci-lint
        run: make lint-golang

      - name: jsonnet-fmt
        run: make fmt-jsonnet && git diff --exit-code

      - name: jsonnet-lint
        run: make lint-jsonnet

      - name: shellcheck
        run: make lint-shell

  generate:
    runs-on: ubuntu-latest
    name: Generate and format
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - run: make --always-make generate && git diff --exit-code

      - run: make --always-make bundle && git diff --exit-code

  tool-versions:
    runs-on: ubuntu-latest
    name: Validate tools cache
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Use tools cache
        uses: ./.github/tools-cache

      - run: make --always-make tools && git diff --exit-code

  build-bundle-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Install tools
        uses: ./.github/tools-cache

      - name: Build Bundle Image
        run: make bundle-image

  e2e-tests-olm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: e2e tests through OLM
        uses: ./.github/e2e-tests-olm
