apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: monitoring-operator-stack.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  description: Monitoring operator to manage Prometheus and Thanos for easier observability.
  displayName: Monitoring Stack Operator
  icon:
  - base64data: "foobar"
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - monitoring
  - prometheus
  - thanos
  - observability
  links:
  - name: Monitoring Operator Stack
    url: https://monitoring-operator-stack.rhobs.io
  maintainers:
  - name: Filip Petkovski
    email: fpetkovs@redhat.com
  - name: Sunil Thaha
    email: sthaha@redhat.com
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
